BASE_DIR = ../../
LIBS= -lm
TIED_VERSIONS=yes
PROGRAM_OBJS=alignment.o sequence.o
APP_FLAGS=-g -k

#
# Don't change below here 
#

include ../Makefile.version
include $(BASE_DIR)/common/Makefile.common


