#LIBS = 
#PROGRAM_OBJS=

CUTOFF_VERSIONS = manual if_clause
TIED_VERSIONS = yes

BASE_DIR = ../../

#
# Don't change below here 
#

include ../Makefile.version
include $(BASE_DIR)/common/Makefile.common


